#!/bin/bash
# Test bash script to do everything we do

# retrieve and parse volumes and partitions
IFS=' ' read -r -a array <<< "$(echo $(lsblk -b -n -o name,size,mountpoint) | tr -d '\n')"

# find unmounted parition
i=0
for target_volume in "${array[@]}"
do
    [[ "$target_volume" == "sd"* && "$target_volume" != *[[:digit:]]* && "${array[ "$( echo "$i + 4" | bc )"]}" != *"/"* ]] && break
    
    i=$( echo "$i + 1" | bc)
done

# get size of drive to partition
target_size="$( echo "${array["$( echo "$i + 1" | bc )"]} / 1024^3 - 5" | bc )"

if [[ "$1" != *"-f"* ]]; then
	read -p "/dev/"$target_volume"1 will be imaged and resized to $target_size GB.
Is this OK? (y/n) " -n1 OK

	[[ "$OK" != "y" && "$OK" != "" ]] && exit 1
fi

printf '\nNow I would do the stuff'
# apply image, create sdx1
# echo imaging /install/pcf.img to /dev/"$target_volume".
# time cat /install/pcf.img > /dev/"$target_volume"

# # grow partition
# sudo parted /dev/"$target_volume" resizepart 1 "$target_size"G

# # resize filesystem to match partition
# sudo e2fsck -f /dev/"$target_volume"1
# sudo resize2fs -p /dev/"$target_volume"1
# #reboot