#!/bin/bash

# define text types
bold=$(tput bold)
normal=$(tput sgr0)

# retrieve cpu info
cpu="$(cat /proc/cpuinfo | grep 'name' | uniq )"
cpu=${cpu##*: }

printf "\nYou are running on: ${bold}$cpu${normal} \n\n"

# retrieve and parse volumes and partitions
IFS=' ' read -r -a array <<< "$(echo $(lsblk -b -n -o name,size,mountpoint) | tr -d '\n')"

# find unmounted parition
i=0
for target_volume in "${array[@]}"
do
    [[ "$target_volume" == "sd"* && "$target_volume" != *[[:digit:]]* && "${array[ "$( echo "$i + 4" | bc )"]}" != *"/"* ]] && break
    i=$( echo "$i + 1" | bc)
done

# get size of drive to partition
target_size="$( echo "${array["$( echo "$i + 1" | bc )"]} / 1024^3 - 5" | bc )"

printf "${bold}/dev/"$target_volume"1${normal} will be imaged and resized to ${bold}$target_size GiB${normal}.\n\n"

[[ "$1" == *"-t"* ]] && exit 1

# install pv if necessary
[[ $(dpkg-query -W -f='${Status}' pv 2>/dev/null | grep -c "ok installed") -eq 0]] && apt-get install pv

# apply image, create sdx1
pv </install/pcf.img >/dev/"$target_volume"

# grow partition
sudo parted /dev/"$target_volume" resizepart 1 "$target_size"G

# resize filesystem to match partition
sudo e2fsck -f /dev/"$target_volume"1
sudo resize2fs -p /dev/"$target_volume"1

# reboot into new image
(speaker-test -t sine -f 800 )& pid=$! ; sleep 0.3s ; kill -9 $pid
reboot
